### ISSUE TITLE
Entering tvdb ID does not take you directly to show.

### ISSUE THREAD

**Issue by purevertigo** [pymedusa/Medusa#10313]
When entering tvdb ID directly into search box. For example.
366924

the app still lists all the related shows and not the actual show.

**Comment by p0psicles** [comment]
That's because it's a shared search field. And some show titles contain my only numbers.

**Comment by purevertigo** [comment]
Thanks for commenting @p0psicles but even if I only select tvdb still doesn't work. I'll attach a screenshot.
![Screen Shot 2022-02-05 at 22 22 49](https://user-images.githubusercontent.com/6506461/152640047-002e15ca-7062-4ca4-b79a-5560d816056c.jpg)

**Comment by p0psicles** [comment]
With shared I mean. It's. A search field that can have a value to search by Id and search by title. We don't know what a user is searching for.

For example. The show `1400`. Should I search by title or I'd. So that's when searching by number. It's always returning. A show by Id. And the other search by title results.

**Comment by purevertigo** [comment]
OK. That makes sense. Can I turn off search on the fly?

**Comment by p0psicles** [comment]
> Can I turn off search on the fly?

what do you mean?

**Comment by purevertigo** [comment]
like only search for that specific term or word and exclude everything else?

**Comment by p0psicles** [comment]
No you cant
