### ISSUE TITLE
Daily search offset Max limit is not large enough... 

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#10558]
Hi,
There seems to be a situation when a show episodes releases are being advanced by one week. This is now the case with Fear the Walking dead" - ep 13 is out now instead of the 16th, and everything seems to be released one week earlier. Unfortunately, Indexers are not up to date with this,  so the only W/A is using this offset we added. Sadly, there is a limit in the Edit field - of 1 week (168 hours). 

I was thinking this can be changed to a limit of  ~2 weeks (or at least 8-10 days), so to cover situations like this one now. Sounds easy enough... What do you think?

**Comment by mmhere** [comment]
The extra time span would indeed be nice due to the way that some channels release stuff early over their pay-for streaming services.

To note what is happening here:  the indexers usually record the "air time" when the show goes at its official broadcast/transmission time (over the air or via cable, etc. -- the so-called "free" access).  One could say that technically the indexers are correct in using this official time.

Some outfits let one sign up for their private pay-for streamer service to view shows early.  That's what is happening here.  Sometimes the show is as much as a week ahead on the streamer as compared with the "network", while some others stream them a few days ahead of time.

**Comment by p0psicles** [comment]
Sure I can up the offset

**Comment by p0psicles** [comment]
bumped to 678 (4 weeks)
