### ISSUE TITLE
Need to  RE-try to connect to Medusa service on broken connection; Refresh of home page with logo-press

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#10761]
The medusa GUI is not showing the home page after failed connection (usually after Windows startup & Browser auto-startup)
**To emulate and Reproduce**
1. Stop medusa service and close the browser (make sure to be on /home/ page
2. re-start  the browser.  Try to connect  and fail
3. Start medusa server . Medusa will not re-connect
4. Press the medusa logo , medusa will not show the shows' list
5. refresh the browser page - everything is fine
**Expected behavior**
1. Medusa should keep trying to connect to the service, say once every 5 seconds
2. Pressing Medusa Logo when on the home page - should refresh the home page, this will also be consistent with pressing the logo from other pages and moving to home.

**Screenshots**
![image](https://user-images.githubusercontent.com/2458280/173493779-2cab8801-7bb1-443e-8e5d-448e2e0aa3a1.png)

**Medusa (please complete the following information):**
<html><body>

Medusa Info: | Branch:                 master                  Commit:                 e4870f8f4a322e67c77434597ccc09aa6524aa05                  Version:                 0.5.29                  Database:                 44.19
-- | --
Python Version: | 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.1n  15 Mar 2022
OS: | Windows-10-10.0.19044-SP0

</body>
</html>Medusa Info: 	Branch: [master](https://github.com/pymedusa/Medusa/tree/master)
Commit: [e4870f8f4a322e67c77434597ccc09aa6524aa05](https://github.com/pymedusa/Medusa/commit/e4870f8f4a322e67c77434597ccc09aa6524aa05)
Version: [0.5.29](https://github.com/pymedusa/Medusa/releases/tag/v0.5.29)
Database: 44.19
Python Version:	3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
SSL Version:	OpenSSL 1.1.1n 15 Mar 2022
OS:	Windows-10-10.0.19044-SP0

**Comment by p0psicles** [comment]
The medusa UI is build using a SPA (single page application). What you are asking is to implement PWA (progressive web app), or also called Service Workers. Which is something that we will do at some point. But not that high of a prio.

Because it's a SPA, clicking the Logo will direct you to the Home route and not refresh the entire page. You don't want to reload it the entire page when you click the logo, because that's something you want to prevent when the page loads fine. The idea of a SPA is to load a minimum amount of data to do a first render. And hydrate the page with additional data using json requests when it's needed.

**Comment by rafi-d** [comment]
>So if it couldn't connect, just click the refresh button.
Yes, I already said that it works... Still what's so hard in making it refresh with the logo click WHEN it is already on the home page (until you implement PWA)?

**Comment by p0psicles** [comment]
Usually you don't want to behave a link different depending on what page you are. Cause a user likes predictable behavior. So that's why i'm not really a fan of that.

Although I could see if I can catch connection errors and set a global flag. So only have it refresh when there are connection issues. But also that i'm not to sure about tbh.
