### ISSUE TITLE
Vacuum on cache db slows boot up process

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1350]
**Branch/Commit:** develop
**OS:** Ubuntu 14.04
**What you did:** Boot up Medusa
**What happened:** The "boot process" too a "long" time to finish, almost 2m for just the cache vacuum, during that time the UI wasn't served by the server
**What you expected:** For the db vacuum to not impair the UI load up, or to be faster (unlikly to happen)
**Logs:**

```
2016-10-27 22:43:36 DEBUG    MAIN :: [c7cab9a] AddIndexerUpdateSchema upgrade not required
2016-10-27 22:43:36 DEBUG    MAIN :: [c7cab9a] Performing a vacuum on the CACHE database
2016-10-27 22:44:52 DEBUG    MAIN :: [c7cab9a] Checking database structure...failed.db
2016-10-27 22:44:52 DEBUG    MAIN :: [c7cab9a] Checking Initial Schema database upgrade

```

**Comment by fernandog** [comment]
1minute and 16seconds

if you don't do this your DB could end up with 1GB size and it will take a lot more to load. In the end you will still need to run VACUUM

**Comment by OmgImAlexis** [comment]
@fernandog @duramato can I close this? It seems this is mainly an issue on setups with slow IO. On both my Macbook as well as UNRAID server I don't see VACUUM taking more than 10 seconds on start. Since you should be running Medusa 24/7 this isn't a huge issue as well as the fact that without it like @fernandog stated you'd end up with a massive DB so the tradeoff seems worth it.

We're also looking at moving to an ORM so the SQL issue here would go away for the most part.

**Comment by labrys** [comment]
Personally I think we should remove the vacuum call.  Unless you are doing frequent inserts and deletes the amount of fragmentation should be reasonably minimal.  Instead of being done at startup, imo it should be done either on a (fairly long) schedule (where it can be done in a thread and thus should not generally impact performance.  Besides we want to be able to get the UI available as early as possible) or it can be done after a mass delete (e.g. removing a series with > X episodes) or lastly it can be implemented as an option in the UI to be invoked as needed.

**Comment by labrys** [comment]
That said, much more important is the ridiculous db calls made on startup which SQLA wouldn't help (and might even slow down).  The cache vacuum took 8 seconds (could take much longer on a system that isn't rebooted as often).  By contrast, the remainder of the startup took 88 seconds after the cache vacuum.  

For example hitting the `xem_refresh` table nearly 1500 times which could likely be replaced by a single `select * from xem_refresh`.   An equal number of hits to 'tv_episodes', also replaceable by a `select * ...`.  Those two calls combined account for 25 seconds during my startup and nearly 3000 calls to the db.  By contrast, replacing those with `select * ...` would instead take about 300 ms.  As a side-note, it hits every row of `xem_refresh` twice.
