### ISSUE TITLE
report_guessit not guessing alias

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#1889]
I noticed with other shows if the dir has `name` and the file has `name (year)` the `name (year)` will be added as an alias but that's not happening for shows with names like so.

```
# guessit: 2.1.2.dev0  rebulk: 0.8.3.dev0
? /downloads/Shadowhunters.S02E01.720p.HDTV.x264-FLEET/Shadowhunters.The.Mortal.Instruments.S02E01.720p.HDTV.x264-FLEET.mkv
: season: 2
  episode: 1
  screen_size: 720p
  format: HDTV
  video_codec: h264
  video_encoder: x264
  release_group: FLEET
  title: Shadowhunters The Mortal Instruments
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 0.190764904022
```

**Comment by medariox** [comment]
This should be reported to guessit.

**Comment by OmgImAlexis** [comment]
@medariox did this and had @ratoaq2 tell me to report it here.

**Comment by medariox** [comment]
Ah sorry, thought standard guessit had ```alias```, nvm then.

**Comment by ratoaq2** [comment]
There are a few things:

- I added `alias` to our guessit to handle country and year. E.g.: `House of Cards (US)`, `House of Cards (2013)`. Later I added an alias concatenating `title` + `alternative_title` due to some anime names and releases in different languages.
- Standard guessit has `title`, `alternative_title` and `episode_title`.

The correct input to proper detect the `title` is to have a separator `.-.`:
```
? /downloads/Shadowhunters.S02E01.720p.HDTV.x264-FLEET/Shadowhunters.-.The.Mortal.Instruments.S02E01.720p.HDTV.x264-FLEET.mkv
: title: Shadowhunters
  season: 2
  episode: 1
  screen_size: 720p
  format: HDTV
  video_codec: h264
  video_encoder: x264
  release_group: FLEET
  alias: Shadowhunters - The Mortal Instruments
  alternative_title: The Mortal Instruments
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 0.079274892807
```

I don't know how to fix this issue easily. Is this a single occurence? or there are more of the same?

**Comment by OmgImAlexis** [comment]
This happens with a handful of my shows but it's not always expected as different groups realise with and without the alias for different shows.

You may need to look into other shows for this but I would expect if the dir and file are exactly the same the extra between the title and SXXEXX would be the alias. I haven't seen any other data put there before.
