### ISSUE TITLE
[Improvements] Season pack search

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#1970]
Hi,
This issue is only for non-english languages.

When I looked debug logs, I saw that for season search the url looked like :
http://www.nyaa.se/?sort=2&term=ShowName+Season&cats=1_0&page=rss&order=1

but in others languages Season should be replaced.
French : Season => Saison
http://www.nyaa.se/?sort=2&term=ShowName+Saison&cats=1_0&page=rss&order=1

It's a lot more successful :)
If we compare :
https://www.nyaa.se/?page=search&cats=0_0&filter=0&term=Season+VOSTFR
https://www.nyaa.se/?page=search&cats=0_0&filter=0&term=Saison+VOSTFR

"VOSTFR" can be considered as a required word :-)

Thanks a lot for your work, 
I am sure that you can bring a lot to this software :)

**Comment by p0psicles** [comment]
Thing is, anime is really bad in keeping to a certain standard. So I wouldn't mind implementing something for this. But then I'd like to know the return of investment. Because we could check in which language you have indexed your show, and based on that, get a translation. But then it wouldn't find any results that do use 'season'.

Also some season packs for anime use: 'S2', 'S3'. Others use '1st Season', '2nd Season'. And I know a few more.

**Comment by IDerr** [comment]
Yeah, that's a big problem.
But for example on t411(french torrent provider), the word season is automatically converted to saison,

The return of investment for this feature is really low. In fact, I created this issue only to report the problem.
I don't know if that affect others languages.

**Comment by IDerr** [comment]
It's a clone of #2160 , the other issue is more accurate, I think you can close this one
