### ISSUE TITLE
NyaaTorrent does not give back results when using non-zero padded episode numbers

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#1978]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** Develop
**OS:** windows/linux
**What you did:** Searched for show 'Youjo Senki' episode 2.
**What happened:** NyaaTorrent gave back no results.
**What you expected:** Around 5 results.
**Logs:**
```
PASTE LOGS HERE
```
It seems that when searching nyaa, the show + non padded absolute ep number is used. Meaning for Youjo Senki, is searches using the string: 'Youjo+Senki+2'. All releases for Youjo Senki are released with a padded episode like: ```Youjo Senki Saga of Tanya the Evil - 01 [720p][AAC][07B357FF].mkv```.
There are no wildcards available that we can use for this.

**Comment by IDerr** [comment]
Hmm, it's searching with 02 for ao no exorcist and it's getting snatched, it's weird...
And all releases for Ao no exorcist are padded...

**Comment by p0psicles** [comment]
Yes that's by design. As I made an exception for season exceptions. So if it's a seasion exception it now uses 02. If it's not, it will use absolute number, and now that is '2'. But nyaa doesn't like that.

**Comment by IDerr** [comment]
Yeah, not really Nyaa, but it's like a convention to name episodes like that.

**Comment by p0psicles** [comment]
Sickrage has recently also made the change to double digit. Well they moved to three digit before that, don't why youd want that. but sure. I think we should do the same.

**Comment by IDerr** [comment]
In fact, the real way to name it, it's with 3 digits, but no one respect that.

**Comment by IDerr** [comment]
It's more like : 
Showname 01-09
Showname 10-999

**Comment by p0psicles** [comment]
They did some more canges like first try double digit, then fallback to three digit padding.
https://github.com/SickRage/SickRage/commit/9b6c552e9fb496d6df5ad741a4a6e1001d164739
Apparently some providers require that, as some shows release in 001, 002, 003.

**Comment by IDerr** [comment]
I think that try both (2 and 3 digits) like them is a good idea.

**Comment by h3llrais3r** [comment]
> They did some more canges like first try double digit, then fallback to three digit padding.
SickRage/SickRage@9b6c552
Yes I implemented this a few days ago. 😄 The problem is that most series (with less than 100 episodes) are labeled with 2 digits. (Cfr HorribleSubs releases). But in order to fiill keep the official scene numbering, I implemented the fallback to 2 digits in case nothing is found with 3 digits.

**Comment by duramato** [comment]
Scene rules are for S01E01 not absolute numbering, that's what fansub groups made up.

**Comment by p0psicles** [comment]
Hi h3llrais3r, yes thanks for that! I was already playing with the idea, as I recently improved the episode numbers used for anime season scene names. Which I also started to use double digits for.

**Comment by h3llrais3r** [comment]
No problem. I found it out this weekend that it wasn't working like expected and tried to fix it for as many scenario's as possible. However, anime naming is not always very consistent, so I think it's difficult to have it working in each scenario.
I recently discovered another scenario: I tried to download the 720p versions of 'JoJo's Bizarre Adventure (2012)', but it always fails the first time. When I run the search again, it always finds it.
The problem is located at https://github.com/SickRage/SickRage/blob/master/sickrage/providers/GenericProvider.py#L211-L212 , so probably in your code at https://github.com/pymedusa/Medusa/blob/master/medusa/providers/generic_provider.py#L248-L249 as far as I can see.
The parsed season number does not match the scene number...
I'm not sure if we can do anything about it?
In case you could find it, please let me know 😄

**Comment by p0psicles** [comment]
I'll try it with this branch. We've made allot of improvements since we separated from sickrage. One of them is using guessit for parsing. Although we still need to refine that for anime parsing.

**Comment by p0psicles** [comment]
Is it a specific season that you had trouble searching for?

**Comment by h3llrais3r** [comment]
season 2 and 3. For season one there was a batch.

**Comment by p0psicles** [comment]
I'll not be available for a while. Let me know if something is not working as expected.

**Comment by h3llrais3r** [comment]
I think you have the same problem (but a little different).
Please retry with an empty cache.
I did a checkout of develop branch, configured only nyatorrents as provider and added 'JoJo's Bizarre Adventure (2012)' as anime.
First forced search of an episode in each season gives no results (but it puts all results in cache).
If you then do a new search again (same episode or other episode of the same season) you get a match and it's downloaded.
So it's a bit different, but probably the same issue (I think you are handling the cache a bit different).

**Comment by p0psicles** [comment]
That's not really a reliable test. Because with removing the cache, you also remove all your collected scene_exception. It will need to get these from thexem.de again. So trying without those, it's not finding any.

**Comment by h3llrais3r** [comment]
I mean I started completely from scratch. So with no db and cache, added the anime and did the search ;)

**Comment by h3llrais3r** [comment]
Debug log added.

**Comment by p0psicles** [comment]
The problem comes from thetvdb using 3 season, where the scene uses 4. Medusa is losing track somewhere while parsing it. As it's parsing it back to "indexer" season 4, while it should parse it to indexer season 3. This will take me some more time, to fully grasp. But now that @ratoaq2 is back ;-), we'll have experts on searching, parsing and indexers.

**Comment by p0psicles** [comment]
Never mind i'm a dumb ass, i didn't have scene numbering enabled. That's why it wasn't using xem mapping.

**Comment by p0psicles** [comment]
Back to the test. You shouldn't erase cache.db and test. Because by the time your doing your first search, chances are high, the cache.db's scene_exceptions table hasn't been populated with the season scene names. And it needs to that know that for ex. 'JoJo Bizarre Adventure - Diamond is Unbreakable' matches season 4 of xem mapping and season 3 of tvdb indexer.

What you could do is, try to access the cache.db table, and perform a ```delete from 'nyaatorrents' where indexerid = 262954;```.

And then again perform a manual search. Then clean again and try a forced search. There shouldn't be much difference between those two. Only the benifit of manual search is, you will see all results.

**Comment by p0psicles** [comment]
Good news. I was able to reproduce it. You are absolutely right. Doing a forced search, first time it does not snatch it. Running it anther time does snatch it.

**Comment by p0psicles** [comment]
@h3llrais3r , please take a look at this branch: #1997. I think I fixed it. But I needed to touch some old code. So will need to do some testing first.

**Comment by h3llrais3r** [comment]
I'll have a look at it right right away. I'll keep you posted. 👍

**Comment by p0psicles** [comment]
I fixed that issue but caused another bug. I'm currently refactoring that method. Will update it later today.

**Comment by h3llrais3r** [comment]
I also checked a bit more in detail and it seems to have a mismatch when compairing at https://github.com/pymedusa/Medusa/blob/master/medusa/providers/generic_provider.py#L246-L251

If we have anime and scene_numbering: the parsed result still returns the indexer season and number.
In our case this is f.e. season 3 episode 39 (last aired episode). However, according to the scene numbering, this is season 4 episode 39 and it's ignored during first scan. However, the episode is stored in the cache as season 3 episode 39. This results in the next scan to find a direct match from the cache.
So I see 2 solutions: 
1. Fix the compare at https://github.com/pymedusa/Medusa/blob/master/medusa/providers/generic_provider.py#L246-L251 (I'm just wondering: shouldn't we just compare the absolute numbering when is_scene is true, instead of comparing scene_episode and scene_number with parsed_episode and parsed_number?)
2. separate cache from match and do match after everything is added to the cache.

**Comment by p0psicles** [comment]
I'll have to check that again. I looked at that yesterday, and imo that looked alright. You have to keep in mind, that eventually we want to use the scene season/ep values to search, and map these eventually back to the indexers season/ep. So in the cache tables we'd like to only have the indexers season/ep. In this case season 3 episode 39. For Jojo's there shouldn't be any season 4 references in the cache.db.
