### ISSUE TITLE
Research from t411 doesn't work

### ISSUE THREAD

**Issue by Marbellasaad** [pymedusa/Medusa#2148]
Hello,installed Medusa,configurated all,but when i try to search anything with T411 the alert say me "we have founds results" via manual search but nothing appear.

Ex : http://prntscr.com/e84pzi

But : http://prntscr.com/e84q5y

Here is my log 👍 

2017-02-13 12:27:10 INFO     SEARCHQUEUE-MANUAL-274431 :: [T411] :: [b8f309a] Performing episode search for Gotham
2017-02-13 12:27:10 INFO     SEARCHQUEUE-MANUAL-274431 :: [b8f309a] Using manual search providers
2017-02-13 12:27:10 INFO     SEARCHQUEUE-MANUAL-274431 :: [b8f309a] Beginning manual search for: [Gotham - S03E11 - Mad City Méfiez-vous du monstre aux yeux verts]

It doesn't go more then this.

**Comment by medariox** [comment]
You are right, the message is confusing. Actually the search found some results, but for other episodes - that's why you get the "found results" message. That provider has no results for that specific episode you are searching for. I agree we should improve this, but it's just the wrong message. About the log: that's all you see if you haven't enabled Debug logging (and as normal user, you shouldn't).

**Comment by Marbellasaad** [comment]
Strange because it really doesn't found anything

**Comment by medariox** [comment]
@Marbellasaad 
That probably means it found results for other seasons. You can enable Debug logging to see exactly what the search found.

**Comment by fernandog** [comment]
@Marbellasaad in the manual search page, in the URL add in the end:

&show_all_results=0 and load that URL. 
see if there is any recent results found

**Comment by Marbellasaad** [comment]
Ok,i reinstalled everything and it works now,thanks guys.
