### ISSUE TITLE
Schedule wrong default sort order

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2307]
It should be by ENDs not Airdate otherwise you will see like this:

Current time 23:51
![1](https://cloud.githubusercontent.com/assets/2620870/23347198/2f4aa888-fc7f-11e6-8369-5908e7a008e5.png)

Sorting by ENDs:
![2](https://cloud.githubusercontent.com/assets/2620870/23347200/35af3a5e-fc7f-11e6-80dd-a7f1e1d103f7.png)

**Comment by OmgImAlexis** [comment]
@fernandog it'd make more sense to sort by airdate and then sort those results by enddate.

**Comment by fernandog** [comment]
No because a show airdate can start at  22:30 and end 23:55 for example. The order would be wrong.

The END date that tell us if is wanted or not. Not airdate

**Comment by Thraxis** [comment]
Isn't this the kind of thing saveSort is there for?  I prefer the default sort... you prefer sorting by end date.... both of us clicks the sort we want and it's always the way we want it.

**Comment by Thraxis** [comment]
And part of the reason I say this is because ENDS is not exactly a valid end time for a show as it's calculated from Start Time + Runtime = End Time.  Which in the US tends to be wrong as it doesn't account for commercial time just that Medusa will start searching at that time. which in all rights it should just start searching when the show starts

**Comment by fernandog** [comment]
ok. valid point using saveSort
