### ISSUE TITLE
Ebuild for gentoo!

### ISSUE THREAD

**Issue by ghost** [pymedusa/Medusa#3147]
Hiya, 

Just wanted to say I've made a working, if not slightly hacky ebuild for Gentoo. 
It's located here: https://gitlab.com/_j/overlay/tree/master/net-nntp/medusa

I tried using @YogSottot's initscript but couldn't get it running, so I've slightly modified /etc/conf.d/medusa and /etc/init.d/medusa from here: https://gitlab.com/salfter/portage/tree/master/net-nntp/sickrage/files
All credits go to @salfter, I've simply just changed his ebuild where needed! 

Thanks :) 

EDIT: sorry for not submitting as a PR, I'll try mirroring the repository and fork medusa if needed.

**Comment by OmgImAlexis** [comment]
@bebop-j any updates on this? If you did/do open a PR please link back to here so we can close this once it's merged.

**Comment by bebop-j** [comment]
Hey. I think it's in my overlay commits, I'll sort it out in a few hours

On 28 April 2018 01:54:03 BST, Alexis Tyler <notifications@github.com> wrote:
>@bebop-j any updates on this? If you did/do open a PR please link back
>to here so we can close this once it's merged.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pymedusa/Medusa/issues/3147#issuecomment-385127145

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bebop-j** [comment]
@OmgImAlexis, it's available here: https://github.com/bebop-j/overlay/commit/491db3b0e31f9621bcc1bc784546857c7593cae3

**Comment by salfter** [comment]
I switched my Medusa installation back from FreeNAS to Gentoo a while back...revisited the ebuild I had knocked together previously and updated it.  Since the overlay linked above is now 404, I should probably throw in a link to my updated ebuild: https://gitlab.com/salfter/portage/tree/master/net-nntp/medusa

It has some Python dependencies that aren't in Portage, so your best approach is to use `layman -a salfter` to pull in the overlay and then emerge from there.
