### ISSUE TITLE
[Minor-Bug][Layout] Posters from TVMaze have a different smaller height

### ISSUE THREAD

**Issue by TrendaFet** [pymedusa/Medusa#3455]
I wouldn't really call this a bug, the layout handles the difference in height perfectly, this is more of the fetched image size itself.

The real reason for using TVmaze instead of the other indexers is that for Black Mirror show, for some reason, it fetches the Russian language poster if I use TVDBv2. Even though the title, installation, system and everything is set in English and I am no where near Russia.

I decided to report this just in case. I fully realize this report falls under "pixel perfectionism", and I understand that pyMedusa has limited control on fetched MetaData.

Ideally I would love if we had the option to customize and choose which poster to fetch and use for every show, along with the default settings.

Otherwise, keep up the great work. I absolutely love pyMedusa and will most certainly support it with everything I can and able to.

**Branch/Commit:** master/1a8dc66c7ec9231be0d3444710e476437c9ae1c8
**OS:** Linux-4.9.0-4-686-pae-i686-with-debian-9.3
**Locale:** en_US.UTF-8
**What you did:** Added a TV show using metadata from TVmaze and then other indexers
**What happened:** Posters from TVmaze have smaller height than others
**What you expected:** Same dimensions

![medusa-posters](https://user-images.githubusercontent.com/17427046/33892407-576daf7a-df61-11e7-92d3-3a955073d644.JPG)

**Comment by medariox** [comment]
Thanks for the nice words @TrendaFet!

As you have already stated we have limited control over the image sizes we get from the various indexers. TVmaze provides a different resolution for the poster images. We had to take a decision on how to make it work for us, e.g. we could have cropped it, but that would have meant losing information. That's why we preferred to place the image that way.

About the problem with Black Mirror poster and TVDB; The issue, in this case, is that the Russian poster was incorrectly added to the TVDB as "English".  https://www.thetvdb.com/?tab=seriesposters&id=253463
![poster](https://snapr.pw/i/68bb2f3aa9.png)

Anyway, the poster with the highest rating should have been chosen, so there might be a small bug somewhere after all. We will take a look at this soon.

**Comment by TrendaFet** [comment]
Fully agreed, the team's decision in handling the difference in height is perfect in keeping the layout intact.

Anywho, thank you very much for the effort and looking into the poster rating issue.

Happy holidays!

**Comment by p0psicles** [comment]
The issue with tvdb getting the rusian poster should also be resolved.
It didn't use the highest rated image. We can't do much about tvmaze, unless you've noticed there are other posters available from the site, that we should use instead.

**Comment by labrys** [comment]
@p0psicles tvmaze posters come in 2 sizes `original` which is whatever size the original artwork was and `medium` which is resized to 210x295.

To me it looks like the TVMaze posters aren't centered.   Centering them would probably make this a little less obvious

**Comment by p0psicles** [comment]
Ill give it some attention after the multi indexer Pr is finished.

**Comment by TrendaFet** [comment]
I absolutely love the update and being able to mass-fetch new images for all shows, which completely fixed the problem and added the neat feature of keeping posters and images up-to-date with different seasons.

The response time in not just fixing this issue but adding a whole new improvement is impressive, to say the least.

I sincerely thank everyone in the team for such dedication and awesome work.
