### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 2] No such file or directory: '/config/cache/images/Bose: Dead/Alive.poster.jpg'

### ISSUE THREAD

**Issue by DDA78** [pymedusa/Medusa#3690]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 16:23:38) [GCC 6.4.0]`
**Operating System**: `Linux-4.4.71+-armv7l-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@bd0832551d836713481dd0a93f4118372bb5d963
**Link to Log**: https://gist.github.com/3e6414caa4f73a7e196501ccf45c2e4b
### ERROR
<pre>
2018-01-31 21:50:23 ERROR    Thread-20 :: [bd08325] OSError: 
Traceback (most recent call last):
  File "/app/medusa/medusa/helpers/__init__.py", line 285, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/app/medusa/lib/shutil_custom/__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 2] No such file or directory: '/config/cache/images/Bose: Dead/Alive.poster.jpg'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by heymoe** [comment]
Maybe related to this: https://github.com/pymedusa/Medusa/issues/3658 (read the later comments)

Since items in the cache dir should be named <showID #>.<image type>.jpg and not the actual show name which in this case has a ":" and a "/" in it which is likely throwing a monkey wrench in to the mix from a file system path point of view. 

This issue does seem to be fix in the develop branch right now.

**Comment by OmgImAlexis** [comment]
@DDA78 is this still happening? If so please let me know and I'll reopen the issue.
