### ISSUE TITLE
Github Personal Acces Token

### ISSUE THREAD

**Issue by noodle-** [pymedusa/Medusa#3822]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-3.4.113-bananian-armv7l-with-debian-9.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**What you did:** I selected Github personal acces token as authentication method for submitting new issues, entered my token, and tried to submit an issue from within Medusa
**What happened:** It kept giving me the error message that I should enter my username/password
**What you expected:** I expected the issue to be submitted of course but I also expected to still have to enter my username, as is usual AFAIK when logging into Github through a 3rd party service 

Unless I'm gravely mistaken (or made an error while entering my login info, but I triple checked it) I think the way of logging in with a git token is wrong, it's missing the username field, and can thus not work.

**Comment by abeloin** [comment]
The issue is fixed in the develop branch and will be merge into master in the next release.

There's no need for a username when using a token in Github, see these links for more info:
- https://blog.github.com/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/
- https://developer.github.com/apps/building-oauth-apps/authorization-options-for-oauth-apps/

**Comment by noodle-** [comment]
Cool, learned something new.

Thanks for the info!
