### ISSUE TITLE
[Feature Request] Season folder setting on 3rd step of adding show

### ISSUE THREAD

**Issue by saitoh183** [pymedusa/Medusa#3838]
![image](https://user-images.githubusercontent.com/1534197/37112983-0035fd90-2212-11e8-87e9-2d2b6705c0a2.png)

![image](https://user-images.githubusercontent.com/1534197/37113014-1b4b04f4-2212-11e8-9c7e-e16e67dc13d1.png)

I ask this because if i recall at some point it was there (unless that was in sickrage). When i add anime im always forced to wait for the show to be added and then go in the show and uncheck season folders. It alot of extra time and steps when the option could be on Step 3 like the rest of the settings. When can you have Scene Numbering there but cant set the seasons folders?

**Comment by sharkykh** [comment]
I'm pretty sure "Flatten Folders" is basically "No Season Folders", meaning you have to check it when you add your show so that it won't add episodes into a sub-folders per season.

@OmgImAlexis 
This isn't a feature request per se, but that option does need to be reversed to match the rest of the application (displayShow, editShow, massEdit) to avoid confusion.

**Comment by saitoh183** [comment]
I thought flatten folder meant that the episode is just added to the root folder without a show name folder

**Comment by sharkykh** [comment]
That's probably one of the reasons Flatten Folders was renamed (or refactored) into Season Folders. The latter is much more informative of the function.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/3931
