### ISSUE TITLE
MeGusta & PSA

### ISSUE THREAD

**Issue by Defs3c** [pymedusa/Medusa#3951]
Hi,

Im on a raspberry pi and I'm wanting to download x265 1080p files. However, the uploaders MeGusta and PSA releases do not come under the category of 720p or 1080p, the manual search just says 'Unknown'. Is there any way to fix this? as my only work around is to edit the ignore words and remove x264 and 720p and add the x265 words. This is a problem as some of the less well known series I have do not get 1080p releases and so I cannot download the 720p files as they are ignored.

**Comment by medariox** [comment]
Add `Unknown` as wanted quality.

**Comment by Defs3c** [comment]
I’ve done that but the issue still remains with the conflicting word lists. If i put 720p I’m ignored I cannot download 720p for any of my shows but if I don’t it will be a hit and miss as to whether it’ll download a 1080p version or not

**Comment by medariox** [comment]
Remove any quality from ignored words, that's not what they are made for. Add `720p, 1080p, Unknown` as wanted qualities.

**Comment by Defs3c** [comment]
But the point I’m getting at here is that MeGusta and PSA are recognised as Unknown and so Medusa cannot differentiate between 720p and 1080p. Say I want X TV show in 1080p, it is not possible as when I add Unkown as the quality, Medusa will download either 720p or 1080p based on whichever comes out first because it is not able to tell if it is a 1080p release or not as it is classed as Unknown.

**Comment by medariox** [comment]
It's like that because they don't add the source of the video to the release name (e.g. `HDTV`, `WEB-DL`) and that's why it's not possible to determine the exact quality of the release.

**Comment by Defs3c** [comment]
Is there an option to leave out the source and have medusa just look for the quality?

**Comment by medariox** [comment]
No, it isn't currently possible.

**Comment by OmgImAlexis** [comment]
@medariox maybe we need to add an option to "assume lowest type of quality for unknowns". This would use `HDTV 720p` or `HDTV 1080p` for unknowns just like it does when we process these types.

**Comment by alron** [comment]
For the MeGusta and PSA stuff I set the quality to whatever I prefer and unknown (in this case all of the 1080p variants and unknown), then I'd Set ignored words to "480p, 576p, 720p, 2160p" and required words to "HEVC, h265, x265". 

It'll ignore everything but the 1080p HEVC goodness. 

Change the 720p to 1080p in the ignored words if you want the 720p goodness. 

Works reliably.

**Comment by medariox** [comment]
To do what, exactly? HEVC is a video coding format and it doesn't tell anything about quality.

**Comment by alron** [comment]
Because a lot of people don't care that much about the source, as long as they get the resolution, codec, and file size that works? Unless you're looking for a very specific set of files, most of the quality indicators are interchangeable, and not terribly indicative of actual content quality, just source. 

The current set of hard-coded search parameters are fairly ham-handed. Sure, we can set requires and ignores. But it is a big set of OR parameters without a way to set AND. Plus, with the search just being for name, resolution and source, without SIZE restriction, we get all kinda of fun things that are 10x the size that we want.

If we had the option to search for resolution and codec instead of resolution and source, it'd be pretty awesome. Plus having the ability to set minimum and maximum file size would help refine the whole thing. Maybe user defined search profiles instead of just the hard-coded resolution-source or unknown?
