### ISSUE TITLE
Proxy setting for Telegram notifier

### ISSUE THREAD

**Issue by keerio** [pymedusa/Medusa#4726]
**Is your feature request related to a problem? Please describe.**
Since Telegram is banned in some countries, bot API is unreachable.
Common solution is a usage of Socks5 proxy

**Describe the solution you'd like**
Socks5 Proxy input field for Telegram notifier would work perfect. 

**Describe alternatives you've considered**
I wonder if it is possible to channel all the Medusa traffic through Socks5 proxy?

**Additional context**

**Comment by sharkykh** [comment]
The config option exists: `Config > Advanced Settings > Proxy host`
This setting currently mostly applies to providers, as well as some other web requests Medusa performs.
With an option to enable it for indexers too.
Unfortunately the Telegram notifier code is old and needs updating in order to use this feature.

I also think you'll need to manually install the `PySocks` Python package if you want to use a Socks5 proxy.
```
pip install PySocks
```

**Comment by keerio** [comment]
Thank you for your attention.
I have installed PySocks but cannot confirm if it helps with Socks5 because my Medusa setup cannot find anything with or without proxy. 

However, I hope for Telegram code update and Socks4\5 native support at Medusa package.
