### ISSUE TITLE
Add torrent9.ph provider

### ISSUE THREAD

**Issue by JabbyJabbo** [pymedusa/Medusa#5138]
Hi

Totaly noob to programmation, I decided to register on github because I started to use medusa on my synology nas and I'm digging it!

Still, I have a slight problem, as I use almost exclusively torrent9, as it is, as much as I know, the only public tracker offering so much french and vostfr content.

Fact is, I discovered it is not working on medusa, probably because torrent9 often changes its url...

Is it possible to modify the provider in order for it to be functionnal again?

Thanks

**Comment by sharkykh** [comment]
> Is it possible to modify the provider in order for it to be functionnal again?
> Fact is, I discovered it is not working on medusa, probably because torrent9 often changes its url...

Not because of frequently changing urls, but because we can no longer get the download link directly from the search results, as you must navigate to a torrent details page and only then can you get the download URL. And...
https://github.com/pymedusa/Medusa/issues/4413#issuecomment-399158369
> Looks like Torrent9 removed or changed the `/get_torrent/{name}.torrent` endpoint.
Getting the details page for each result in order to get the download link is not something we want to do.

**Comment by medariox** [comment]
I recommend to use YGGTorrent instead, it's much better in every aspect.
