### ISSUE TITLE
Manual search not working when there are multiple same scene numbers

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#558]
**Intruduction**

More than frequent, talk shows or intrest shows like Horizon, or Panorma have scene releases with the same number for 2 diferent episodes.
Example is : 

```
Horizon.S54E08.Is.Binge.Drinking.Really.That.Bad.PROPER.720p.HDTV.x264-BARGE
Horizon.S54E08.70.Million.Animal.Mummies.Egypts.Dark.Secret.720p.HDTV.x264-C4TV
```

Both beeing _valid_ scene releases

<u>**Issue**</u>

```
tvdb's Season 2015 Episode 5 * matches scene S54E08 
tvdb's Season 2015 Episode 4 ** matches scene S54E08
```

\* with title `Is Binge Drinking Really That Bad?`
*\* with title `70 Million Animal Mummies: Egypt's Dark Secret`

Each matching one of the episodes from above.
When searching for the "first S54E08" , tvdb's Season 2015 Episode 4 it searches fine and shows them in the episode's respective manual search page.
When searching for the "second S54E08" , tvdb's Season 2015 Episode 5 it searches fine **BUT** it does **NOT** show them in the respective manual search page

Log when searching for the "first S54E08" : https://gist.github.com/duramato/f282adb281a6efb39b657249635fe179

Log when searching for the "second S54E08" : https://gist.github.com/duramato/1c5a7b9989c3d23ab66161627c6e840e

Both kept to a "snippet" of one provider to keep them short, and both from usenet. 1st show it beeing added to cache while second isn't.

https://cloud.githubusercontent.com/assets/10121067/15100750/351c7ae0-1574-11e6-8e5f-cf914ad1c8f7.png
https://cloud.githubusercontent.com/assets/10121067/15100773/0ff4348c-1575-11e6-89b5-4f48bae64ab8.png

**Conclusion** (or sort of)

This  is a great exaple of an use for manual search, to select the **exact** release for each episode when there are two of the same, but as is it defutes its porpuse

**Comment by p0psicles** [comment]
Does it work with the other search modes?

**Comment by duramato** [comment]
Forced search doesn't snatch it either, searches fine and even "says" it adds to cache.
Log snippet for forced search: https://gist.github.com/duramato/7495910872a02f77d3ddf253307efe1c

**Comment by fernandog** [comment]
i know what's the issue

**Comment by p0psicles** [comment]
This is the issue. The reverse scene_numbering lookup.
https://github.com/pymedusa/SickRage/blob/develop/sickbeard/scene_numbering.py#L305

This is the full stack:
get_indexer_numbering_for_xem [scene_numbering.py:304]	
get_indexer_numbering [scene_numbering.py:160]	
_parse_string [parser.py:294]	
parse [parser.py:427]	
find_search_results [GenericProvider.py:181]	
searchProviders [search.py:547]	
run [search_queue.py:316]	

As you can see, it's returning int(rows[0]["episode"], for where row has two results.
![image](https://cloud.githubusercontent.com/assets/1331394/15175463/b4767d9c-1766-11e6-8288-e0e48ec6b3ce.png)

![image](https://cloud.githubusercontent.com/assets/1331394/15175485/db816852-1766-11e6-80c5-88bd44dd14f8.png)

I think i'm going with returning a list of tuples, instead of the first one.
And then make sure all calling methods, can handle them. I'm still confident we can make this work with manual search.

**Comment by p0psicles** [comment]
@fernandog your still assigned, you want to handle this?

**Comment by fernandog** [comment]
I prefer you do If you dont mind

**Comment by fernandog** [comment]
How you are going to choose between results?

**Comment by p0psicles** [comment]
Thats A good question. Maybe im not going to. And just show Both results for Both eps.

**Comment by fernandog** [comment]
If you add it, it will make that result multi-episode. Which is not. So when you snatch, it will mark both as snatched

**Comment by duramato** [comment]
They should be separate entries in the cache,  and not as a multi ep imo,  because it would be wrongfully cached and possibly wrongfully  downloaded

**Comment by duramato** [comment]
Another possible occurrence of this is when tvdb lists a special both in specials and as normal ep  and will be mapped to both, if it's on xem or user inputs

**Comment by fernandog** [comment]
We already handle that. We call in code: same day special. Normal is used in this case

**Comment by medariox** [comment]
What's the progress on this? Fixed?

**Comment by fernandog** [comment]
This should be fixed with new db

@labrys

**Comment by OmgImAlexis** [comment]
Any updates on this?
