### ISSUE TITLE
[Feature Request] Medusa Synology App

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#5602]
Hi Team

Is there any way to get the Medusa Synology App added to the Syno Community ?

Thanks

**Comment by p0psicles** [comment]
Someone has created one. But we dont have any syno devs in the team. The idea was to evaluate the package first

**Comment by p0psicles** [comment]
https://www.reddit.com/r/PyMedusa/comments/9qtpio/medusa_package_for_synology_dsm_6

**Comment by pigr8** [comment]
hi, i'm not a dev and i'm very unskilled at coding, the package i made is based and modded on someone other's work to make it fit for Medusa.. for what i know (tested on 4-5 real synology - different arch - and some virtual enviroment) it works without issues, other that tried it reported working correctly, maybe some more feedback before publishing it as some kind of official package.

i don't know how the process with synocommunity works, if it's hosted there the package.tgz inside the spk could contain Medusa itself without the github sync since a new build is released every few weeks, just an idea.

**Comment by LaBoss** [comment]
I use sickbeard-custom and on install change URL to medusa GITHub,

**Comment by HPMSGEN8** [comment]
@pigr8 Thanks

@LaBoss The point of this is to have more then 1 install on your System.  Or have the Official Package so no need to change anything it is all setup and ready to go.

**Comment by neurohacked** [comment]
I'm getting an error when trying to test my Synology DS connection:

WARNING  Thread_4 :: [0c0a735] Error while testing downloadstation connection: No module named downloadstation_client

**Comment by timmakken** [comment]
i would really love to run this on DSM4.x , currently when installed it just does not load the page on port 8083. did someone figure out how to get it to run on this particularly low(old) DSM version?

**Comment by p0psicles** [comment]
@timmakken why not just use the sickbeard-custom package for that?

**Comment by astronyu** [comment]
Would love for this package to have a different default port number than sickbeard-custom.

**Comment by Ltek** [comment]
Does this package auto-update?
