### ISSUE TITLE
[Bug]Search Settings Page

### ISSUE THREAD

**Issue by Tearow** [pymedusa/Medusa#5663]
**Describe the bug**
When you head to Search Settings it shows black screen so background without content

**To Reproduce**
1. Go to 'Gear icon'
2. Click on 'Search Settings'
3. See screenshot

**Expected behavior**
Shows settings of the sare

**Screenshots**
https://imgur.com/a/u0kMi11

**Medusa (please complete the following information):**
 - OS: Synology. Pymedusa/medusa:lastest (docker image)
 - Branch: master 
 - Commit: 0c0a73583452f988c518adeafa75ee1f17987bdf

**Logs:**
<details>

```
Nothing to be found in logs
```
</details>

**Additional context**
you can see some errors in the console. i tried it in internet *throw up* explorer

**Comment by bodhikun** [comment]
I have the same problem!

When I try to go to Search Settings, the page is blank.

reinstalling did not solve the problem.

**Comment by p0psicles** [comment]
Can you paste the chrome console error.
@OmgImAlexis this is master. My search page pr hasn't been merged yet.

**Comment by sharkykh** [comment]
@p0psicles 
https://github.com/pymedusa/Medusa/blob/0c0a73583452f988c518adeafa75ee1f17987bdf/themes-default/slim/views/config_search.mako#L370
It tries to get `clients.torrent[torrent.method].removeFromClientOption`, however if `torrent.method` **isn't** in `clients.torrent` then it becomes `undefined` (`undefined.removeFromClientOption`), which causes the error.
That's my take on it... Maybe `torrent.method` is empty or has an invalid value somehow?

**Comment by p0psicles** [comment]
Ooh, i fixed that already in my pr

**Comment by p0psicles** [comment]
@tearow or @bodhikun willing to test a branch?

**Comment by bodhikun** [comment]
> @Tearow or @bodhikun willing to test a branch?

Sure, what do you want me to do?

**Comment by p0psicles** [comment]
Checkout this branch feature/vueify-config-search

**Comment by xmenxmen** [comment]
I have the same problem!

When I try to go to Search Settings, the page is blank.

**Comment by Tearow** [comment]
> Checkout this branch feature/vueify-config-search

Sure if i know how to do it i am only able to see master at General > Advanced settings

**Comment by Tearow** [comment]
i have the Medusa running on synology docker so i would need to figure it out but i will do it after sleep and work tomorrow. maybe bodhikun could try it. il test tomorrow

**Comment by p0psicles** [comment]
pretty sure it's fixed with the pr. I'll make sure the pr is merged before next release.

**Comment by stappel** [comment]
It is not fixed in 0.2.12 release. the same problem is still there. 

The error in the console is
`[object Error]: {description: "Unable to get property 'shortTitle' of undefined or null reference", message: "Unable to get property 'shortTitle' of undefined or null reference", number: -2146823281, stack: "TypeError: Unable to get property 'shortTitle' of undefined or null reference at Function code (Function code:2:17770) at t.prototype._render (http://192.168.123.10:8083/js/vendors.js?30631:51:32651) at Anonymous function (http://192.168.123.10:8083/js/vendors.js?30631:51:64060) at Ne.prototype.get (http://192.168.123.10:8083/js/vendors.js?30631:51:15939) at Ne.prototype.run (http://192.168.123.10:8083/js/vendors.js?30631:51:16826) at De (http://192.168.123.10:8083/js/vendors.js?30631:51:14970) at Anonymous function (http://192.168.123.10:8083/js/vendors.js?30631:51:11420) at Gt (http://192.168.123.10:8083/js/vendors.js?30631:51:10922)"}`

**Comment by p0psicles** [comment]
Its a different error message, but ill check it out
