### ISSUE TITLE
Do scene exceptions get reset?

### ISSUE THREAD

**Issue by bluelavalamp** [pymedusa/Medusa#5793]
Do Scene Exceptions that are added per show using the Edit->Advanced for the show naturally get removed after a while?  

I have 4 shows that have a 'é' in the title and I've added a scene exception to each where I write the title using an 'e' instead and after a while the scene exception will be removed from the show.  I don't know when or how, but after a week or so the shows don't have any scene exceptions.

Thanks,
Kevin

**Comment by p0psicles** [comment]
No they shouldn't. Something might have happened incidentally during an update.

**Comment by p0psicles** [comment]
@OmgImAlexis I suspect this is because we still have the editShow route in home\handler.py. And this is still used by the mass updater. I think it's fixed when we vueify massupdate, and remove the handler.py editShow code.

@bluelavalamp, did you perhaps use the mass updater in the last couple of weeks?
