### ISSUE TITLE
Incorporate post processing video conversion script

### ISSUE THREAD

**Issue by rrd911** [pymedusa/Medusa#5885]
**Describe the solution you'd like**

I currently use Sickrage with a post processing script that converts various video formats to mp4/aac. To do this I had to install ffmpeg and additional python requirements of the post processing script manually which is a pain to do every time I wanted to get a new build of Sickrage. I have to git pull the script package into the /config directory in order to not loose the settings etc. 

Would it be possible to include the script, ffmpeg and a few python dependencies into the image? 

Or what is the best way to have the additional packages installed when updating the image so as to not have to manually update every time?

**Describe alternatives you've considered**

Current alternative is to manually add the dependencies and the script each time the image is updated. Have to manually update the image instead of using watchtower.

**Additional context**
Post processing script I am using:
https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/README.md

**Comment by p0psicles** [comment]
Ffmpeg is already in it right? Python dependencies i think i think is not a problem. Scripts you can always keep in your data folder.

**Comment by p0psicles** [comment]
Might wanna look out for some conflicting packages as for ex guessit 2. We use guessit 3 now

**Comment by rrd911** [comment]
Didn't see ffmpeg in the image unless I am missing it?

Thanks for taking a look.

**Comment by a10kiloham** [comment]
If docker might make sense to build this into your downloader image instead of Medusa. 
Otherwise why not create your own Dockerfile to pull this image from git, add your own dependencies and then put on Dockerhub?
We could add ffmpeg but that one adds a lot of extra things to the docker image which seems a little overkill since most people don't use it.

**Comment by rrd911** [comment]
I would think that there might be a need to encode files with ffmpeg. I see numerous examples of people asking how to convert files to one format or another (I use Plex and prefer h264/aac/mp4). Makes compatibility with various streaming clients easier.

might be a feature to add into Medusa - media conversion to a format choice with subtitles embeded

Just thought.

for now I am learning more about automating the build process to use someones image, add what I need including the conversion script. Looking to have it automated so that when the image updates the custom image I want is build and updated on my system automatically. Still a newbie at Docket, Compose and Github.

**Comment by a10kiloham** [comment]
Create your own fork of Medusa from the github website. Then edit the Dockerfile to add ```ffmpeg``` on the line just before mediainfo or right after mediainfo so that line would say ```mediainfo ffmpeg gdbm py-gdbm```
From that fork then you can either:
1) run git clone to your local PC then do a ```docker build --tag mymedusa . ``` from that directory. Then use the normal docker run commands you'd normally use except replace the ```pymedusa/medusa``` with ```mymedusa``` or whatever you named it previously
2) create a Docker Hub account, link your github, then create a project there. When done then just use the docker command again replacing ```pymedusa/medusa``` with ```<dockerhubname>/mymedusa``` or whatever you named it

**Comment by rrd911** [comment]
I ended up creating a dockerhub project that build a new image from the latest image and adds what I need.

thanks for the pointers. This can be closed out if it's not a feature that would be desirable. 

https://cloud.docker.com/u/raydiasdockerhub/repository/docker/raydiasdockerhub/medusa_ffmpeg_mp4_automator
