### ISSUE TITLE
RAR archives

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#5938]
Hello,

Any idea on why I am getting this error:

2018-12-30 14:41:11 WARNING  POSTPROCESSOR :: [918cfe7] Failed unpacking archive LaCasaDePapel720p_103_WWW.NEWPCT1.COM.rar: Error: 'Unsupported RAR version, expected 4.x or 5.x, found: archive'

Kind regards

**Comment by medariox** [comment]
As the warning says. They packed the archive with a very old Rar version which we don't support.

**Comment by dkrahmer** [comment]
The error indicates that your unrar application version is not supported, not the file.
I had the same issue because I had a very old version of unrar installed. I uninstalled the old version of unrar that then built and installed the latest version by following the steps on this page: http://www.linuxfromscratch.org/blfs/view/svn/general/unrar.html
