### ISSUE TITLE
nzbToSickbeard.py 'Not enough information to parse release name into a valid show'

### ISSUE THREAD

**Issue by KarmaLlama** [pymedusa/Medusa#6023]
**Describe the bug**
I can't get failed download handling to work using nzbToMedia scripts with Medusa. A post-processing script called nzbToSickbeard.py is configured on SABnzbd. When a SABnzbd download fails the script calls tv.py which in turn calls Medusa but Medusa complains of missing parameters 'Not enough information to parse release name into a valid show'.

**To Reproduce**
Install the nzbToMedia scripts as per https://github.com/clinton-hall/nzbToMedia/wiki/installation

**Expected behaviour**
I expect the ty.py script (invoked by the nzbToSickbeard.py script configured in SABnzbd) to pass the correct parameters to Medusa and for Medusa to find an alternative source to pass back to SABnzbd for it to download the alternative file.

**Medusa:**
 - OS: MacOS Sierra 10.13.6
 - Branch: master

**Logs:**
<details>

```
**TV.py log**
[17:38:41] [DEBUG]::SICKBEARD: Opening URL: http://localhost:port/tv/api/xxxxxxxxxxxxxxxxxxx/?cmd=postprocess with params: {'nzbName': 'Arrow.S07E06.Due.Process.1080p.AMZN.WEB-DL.DDP5.1.H.264-CasStudio.nzb', 'quiet': 1, 'failed': 1, 'proc_dir': '/Volumes/Media/TV Shows/Arrow/Season 7', 'delete_on': 1}

**Medusa log**
2019-01-16 17:38:41 INFO TORNADO :: [918cfe7] /Users/fred/Downloads/complete: Failed download
2019-01-16 17:38:41 INFO TORNADO :: [918cfe7] I did encounter some unprocessable items:
2019-01-16 17:38:41 INFO TORNADO :: [918cfe7] Successfully processed.
2019-01-16 17:38:41 WARNING TORNADO :: [918cfe7] Failed Download Processing failed: None, /Users/fred/Downloads/complete:
2019-01-16 17:38:41 WARNING TORNADO :: [918cfe7] Not enough information to parse release name into a valid show. Consider adding scene exceptions or improve naming for: complete
2019-01-16 17:38:41 INFO TORNADO :: [918cfe7] Failed download detected: (None, /Users/fred/Downloads/complete)
```
</details>

**Comment by KarmaLlama** [comment]
Can anyone provide a link to the API documentation please? I can't find anything to describe the postprocess API call at https://github.com/pymedusa/Medusa/wiki/API-v2.

The error in the Medusa log and reason for failure suggests Medusa is taking the parent folder which is called 'complete' instead of the full path to the failed download folder such as 'complete/folder_containing_the_failed_download'.

'_Not enough information to parse release name into a valid show. Consider adding scene exceptions or improve naming for: complete_'

**Comment by medariox** [comment]
nzbToMedia is calling the API with the wrong arguments.
`proc_dir` should be `path` and a bunch of those don't even exist.

You can see the list of available parameters here:
https://github.com/pymedusa/Medusa/blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/server/api/v1/core.py#L1267-L1280

These haven't been changed since forever.

**Comment by medariox** [comment]
@labrys 
The problem is that `nzbToMedia` is using two methods to trigger the post-processing, depending if the user has the API key set or not.
https://github.com/clinton-hall/nzbToMedia/blob/4896848099298ee2914760c56a66d4ad0674d181/core/forks.py#L65-L70

For the API the required params are the ones I posted above.
For the other method (not using the API) these are the available params:
https://github.com/pymedusa/Medusa/blob/a1d899bc882da047b3d6ff936e8b78b62b169b05/medusa/server/web/home/post_process.py#L24-L25

`nzbToMedia` should really try to stick to the API and actively request the user to use the API key IMO, especially for security reasons.

**Comment by labrys** [comment]
IMO it should be up to Medusa to decide which it officially supports.
If Medusa decides to only officially support api keys with nzbToMedia that can be accommodated. nzbToMedia, however, should not be opinionated on what Medusa users should use if both are supported by Medusa.

As for @KarmaLlama's issue, the Medusa API is not currently supported (and to my knowledge has not been in a long time) as it's API params differ from the SickBeard API.  Support for the API should be fairly trivial to add, but if there are any changes to it then please let us know so we can keep it up to date.
