### ISSUE TITLE
pypy

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#6366]
Hi,
Just a question - since pypy is reported to be ~ x7 times faster :
https://hackernoon.com/which-is-the-fastest-version-of-python-2ae7c61a6b2b

Was porting to it considered/possible at all ?

Rafi

**Comment by medariox** [comment]
It is not planned and would be very difficult to achieve with the many libraries we have and the little manpower. Closing as this will likely never happen.

**Comment by p0psicles** [comment]
Maybe this is something @rafi-d can implement? PR's are always welcome.

**Comment by rafi-d** [comment]
I was just wondering why an effort to port to pypy is not worth it, since some activities here are for performance-sake (View/Py3 ?) , and using GIT compiling will always be faster then interpreters. 

You have mentioned many libraries, so I understand the scope of work is large, followup questions:
1. Do you expect pypy to be able to work on all platforms (cpus) medusa is running on? 
2. Is the fact that some external libraries might be effected - rules this out (the need to re-patch them for every new version of them)?
3. If you had to choose, now that Medusa supports python3, will you select pypy or pypy3 (less stable) ? 
4. Can you point to libraries being used, but not shown here http://packages.pypy.org/ ? 
5. Will  JS/Vue parts still used, and can cause a slowdown, or pypy "warmup" time?

**Comment by gmusgrave** [comment]
I second this request, if it is at all possible to do.

Things have changed considerably on the pypy front since the previous posts in this thread.

As far as I can tell, there are versions for pypy for every platform supported by Medusa. It now supports python 3.7, and pypy3 is stable.

It is supposed to be a direct drop-in replacement for python. There are a few incompatibilities with unusual code or libraries, some of which are resolvable via available extensions for pypy.

Given that I'm sure we would all like to see speedier execution of Medusa (it seems to have bogged down considerably over the last year or so), it seems like pypy should at the very least be investigated. 

Details are here: https://www.pypy.org/

Thanks...

**Comment by p0psicles** [comment]
Yes would be great if someone could pick this up!
