### ISSUE TITLE
Improve Scene Numbering

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#684]
Branch/Commit: d0c1d270f08bc1b84183d81a1ea5b1d70cacc426
OS: Unraid running Sickrage in docker
What you did: Ran manual pp
What happened: 7x21 was detected as S07E20
What you expected: 7x21 to be detected as S07E21
Logs:

```
File /tv/Regular Show/Regular Show - S07E20 - Donut Factory Holiday 1080p WEB-DL.mkv is the same size as /downloads/Regular Show - 7x21 - Chilli Cook-off [WEB-DL 1080p x265 AAC].mkv
```

**Comment by duramato** [comment]
Working as inteded ,disable scene numbering if it isn't your liking... 
http://thexem.de/xem/show/3174

**Comment by OmgImAlexis** [comment]
It'll pulling 7x21 down as S07E20 though which means files are being replaced with the incorrect episode.

**Comment by Arcanemagus** [comment]
Regular Show is quite problematic, each uploader seems to have their own idea for what season 7 should look like. Last time I counted there were 5 different naming schemes for that season out there.

Since nobody is agreeing on it, the scene numbering is useless for that show, as such currently I have that disabled and manually verify every release it finds. I've had to manually find releases for most of this season due to this mess. Seasons 1-6 are fine though...

**Comment by OmgImAlexis** [comment]
Maybe we need to add some kind of warning for certain shows that they're known to have issues similar to how American Dad and a few other shows work since some go by US live tv seasons, some by the network's season, etc.

**Comment by labrys** [comment]
First I'd like to start with a summary of how scene numbering should work.  If I'm off base on any of these points, I'm sure @duramato can correct me.  I'll use [Supergirl](http://thetvdb.com/?tab=series&id=295759) as an example, as its on of the simplest mappings.


##### How Scene Numbering Works:
First we check [XEM](http://thexem.de) to see if the series has a known scene numbering.  In our example, [Supergirl](http://thexem.de/xem/show/2784) does since episodes `S01E04` and `S01E05` were aired in reverse order.  [TVDB](http://thetvdb.com) uses the network's official ordering while scene used the air date order to number the episodes.

Next a search finds `Supergirl - S01E04`.  If scene numbering is enabled for the series, it makes the assumption that `Supergirl - S01E04` is scene numbered and represents TVDB episode `Supergirl - S01E05`.  Next we check the database and see `S01E05` is a wanted episode, marks `S01E05` as snatched and downloads the release `Supergirl - S01E04` from the provider.

During post-processing it finds `Supergirl - S01E04` in the download folder, renames it to `Supergirl - S01E05` (as the show library should always be in TVDB numbering), and marks `Supergirl - S01E05` as downloaded.
 
At this point the library would show `Supergirl - S01E04` as wanted and `Supergirl - S01E05` as downloaded.
 
A later search finds `Supergirl - S01E05`, and snatches, downloads, and post-processes it as `Supergirl - S01E04`.  
 
The library would now be complete with both episodes downloaded.


##### Potential issues with scene numbering
Scene numbering works on the assumption that the releases for that show are all scene numbered.  Unfortunately, there is no guaranteed way to confirm that a release is scene numbered, TVDB numbered, or follows some other numbering, short of downloading the episode and manually confirming (i.e. by watching it).  As mentioned by @Arcanemagus some shows are problematic in that a variety of different numberings are used.  

The manual search feature can prove particularly useful in this situation as it gives more control over selecting a result and a user can be more discriminating during selection.  For example you find you are missing `Supergirl - S01E04` from your library.  TVDB lists the episode title for `S01E04` as *Livewire* and `S01E05` as *How Does She Do It?*.  A manual search for `S01E04` might return a list of releases containing results such as `Supergirl - S01E04`, `Supergirl - S01E04 - How Does She Do It`, and `Supergirl - S01E04 - Livewire`.  Since *Livewire* is the episode you really want, you can select that episode and be certain that you download the episode you really wanted.  

However, even this isn't a perfect solution since the post-processor will see the downloaded `Supergirl - S01E04 - Livewire` release, assume it is scene numbered, and rename it as `Supergirl - S01E05 - How Does She Do It?`.  With scene numbering enabled, to get the desired results without issue, you would need to snatch a `Supergirl - S01E05 - Livewire` release so that it gets renamed correctly to `Supergirl - S01E04 - Livewire` by the post-processor.  The key here is consistency.  If you have scene numbering enabled you should be manually snatching scene numbered results and vice versa.

@OmgImAlexis The issue you have is related to this, although as @Arcanemagus pointed out, it is complicated by the fact that the downloaded release `Regular Show - 7x21 - Chilli Cook-off [WEB-DL 1080p x265 AAC].mkv` is neither scene numbered nor TVDB numbered.  Per TVDB *Chilli Cook-off* should be `S07E19`, per scene it would be `S07E20`, however that release is numbered as `S07E21` which matches neither.  Manual scene numbering could resolve this for a single episode, however even that has it's drawbacks since it can't deal with inconsistencies in numbering either.

Instead of a warning, possibly an Issue listing problematic series?  That way the community can work to maintain the list, freeing dev time for actual development.  @ratoaq2's work towards a guessit-based name parser could help in some of these instances (for example scene groups are most likely to follow scene numbering and episode title parsing could help match others).
