### ISSUE TITLE
Quality Sizes

### ISSUE THREAD

**Issue by coop73** [pymedusa/Medusa#7075]
Would like to be able to change search sizes of say 720p to only search for files from 500mb to 1500mb.

**Comment by coop73** [comment]
I know that is the way CouchPotato has it setup.

**Comment by rafi-d** [comment]
@coop73 
Want to try my private implementation for this?

**Comment by medariox** [comment]
Already in the requests list.

**Comment by p0psicles** [comment]
@coop73 sure. drop a pull requests and we can review.

**Comment by rafi-d** [comment]
> 
> 
> @coop73 sure. drop a pull requests and we can review.

It was my suggestion... There is already an old PR for it (which needs my update to 0.34):
https://github.com/pymedusa/Medusa/pull/4133#issuecomment-391014436

Basically the same idea - use minsize=xx /maxsize=yy among the "ignore words", and auto-normalize per quality,  until you are done with your new veu/GUI... Works great here since then.
