### ISSUE TITLE
Manage torrents menu link does not work

### ISSUE THREAD

**Issue by johnvick** [pymedusa/Medusa#7701]
Medusa Info: | Branch: masterCommit: d0c136d7a528a471b51676140bd35d24d97f65c6Version: 0.3.11Database: 44.14
-- | --
Python Version: | 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-4.15.0-58-generic-x86_64-with
Locale: | en_US.UTF-8

Don't use often but noticed the link it produces is wrong.

**Comment by rafi-d** [comment]
Works Ok on Windows 10.

**Comment by rafi-d** [comment]
It is just using  the link YOU have provided in the search settings. How can it be related to medusa ?

**Comment by johnvick** [comment]
Well this link works for torrent downloads but not with the manage torrents link.

**Comment by rafi-d** [comment]
So we are not talking of the same link. Look at your search settings for your torrent client.

**Comment by johnvick** [comment]
In /medusa/config/search

I have selected Deluge web gui and then put its address in

https://my.remote.deluge/deluge/

Tested and works.

(Is the the link you were referrng to?)

But
/medusa/manage/manageTorrents/ brings up the wrong address or does not pass it on correctly to the browser resulting in:

https://mydns.org/medusahttps://my.remote.deluge/deluge/ 

which obviously doesn't work.

**Comment by rafi-d** [comment]
Here is an idea: have a look in your config.ini file, and see which other configuration has "mydns.org"...

**Comment by johnvick** [comment]
I don't see any references to mydns.org in config.ini.

https://mydns.org/medusa is the address I use to access Medusa.

**Comment by medariox** [comment]
Was useless and ahs been removed.

**Comment by adocampo** [comment]
Sorry to continue this thread, but it doesn't work for me either now.
I migrated from sickrage to medusa since the begining, so I didn't entered this submenu in years. But recenty I had problems with my transmission and I wanted to change the settings on medusa.

I have all dockerized, both transmission and medusa, transmission is running on the ip `172.28.0.4` medusa can reach it normally and it adds torrents just fine. I have my own domain and a nginx reverse proxy publishing the services both in my LAN and in the Internet, on domains torrent.domain.com and medusa.domain.com. So far, so good.

When I click on https://medusa.domain.com/manage/manageTorrents/, it loads for a  while and when it timeouts, it shows the URL http://172.28.0.4:9091, which is the transmission docker instance's IP and port, which obviously cannot be reached by any other computer.

I've tried to manually reset the URL on `config.ini` file on the `torrent_host` parameter, where I can see the aforementioned URL, but when I restart medusa's docker, it brings back the original value.

My bet this parameter is saved in any of those .db files, but I cannot figure how to change it.

Can anyone shred some light in this issue, please?

**Comment by adocampo** [comment]
Oh, just saw I cannot ping from medusa's docker to transmission's docker... that must be the problem, I guess. I will find what's happening here and report back
