### ISSUE TITLE
Unable to find TV show

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#7712]
Hello,

I am trying to find TV Show, called: You.

It does exist as per TMDB:
https://www.themoviedb.org/tv/78191-you?language=es-ES

But when I search it in Medusa it timesout:

![image](https://user-images.githubusercontent.com/3207791/74084542-6fc20400-4a70-11ea-8d19-897b100ab5a8.png)

Any way to fix it?

Kind regards

**Comment by elpedriyo** [comment]
Hello,

I was able to make it work by expanding timeout in settings, but a lot of tv shows are showing.
Is there any way I can get into TMDB and take the ID, and search by ID, or something else, to filter and find the show easier?

Kind regards

**Comment by pnoeric** [comment]
(Completely random interface suggestion to the devs: add a way for a user to specify an ID number for a show from the current provider. I.e. this is TMDB 78191, so if the user enters something like "id:78191", it would just pull that show based on the ID number instead of doing a search. Please feel free to ignore this idea if it's stupid. 😀)

**Comment by p0psicles** [comment]
No it's a good idea

**Comment by medariox** [comment]
Added.
