### ISSUE TITLE
Encountered an error while loading folders: timeout of 180000ms exceeded

### ISSUE THREAD

**Issue by carloscebrian666** [pymedusa/Medusa#8341]
Hello,

I am starting in Medusa and I have a problem with the import of the series that are located in Google drive, approx 400, it reads them all but when it should show me it gives me the error Encountered an error while loading folders: timeout of 180000ms exceeded.

Could you please help me because it is desperate and if you need any additional information.

Thank you very much Team

**Comment by realbuz** [comment]
having the same issue

**Comment by realbuz** [comment]
so I decided to look a bit into this because based on debug log, it seems like the UI API call times out before the process is done scanning (I was about 30-60 seconds short).

I am running medusa in a docker.  I opened a shell to the docker and used vi to edit the medusa/theme/dark/templates/addShows_addExistingShow.mako file (assuming this is the theme you are using).  then just changed the line: 

requestTimeout: 3 * 60 * 1000 to requestTimeout 5 * 60 * 1000

save out and reload the web page

hope this helps someone.

**Comment by p0psicles** [comment]
Yeah you increased the timeout to 5 min. But maybe that's enough time for your folder. Someone else might need 10 min. Or 25 min.

**Comment by realbuz** [comment]
yup, 5 was enough for me.  if someone's reading and attempting this, I'm guessing they should have the smarts to be able to decide and adjust to their needs.

**Comment by medariox** [comment]
Use multiple folders.
